Add support for typing.Required, NotRequired
Previously, annotating a `TypedDict` field with one of the `Required`
and `NotRequired` wrappers introduced in Python 3.11, the library would
raise the following error:

> TypeError: issubclass() arg 1 must be a class

Fix that error by adding support for `Required` and `NotRequired`.

Partially addresses issue rnag/dataclass-wizard#121. [1]

[1]: https://github.com/rnag/dataclass-wizard/issues/121